name: recipe_finder
description: "AI-Powered Recipe Finder app"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  flutter_svg: ^2.1.0
  flutter_gemini: ^3.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  uuid: ^4.4.2
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  path: ^1.9.0
  dio: ^5.8.0+1
  l10n_flutter: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  lock_orientation_screen: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/